deploy:
  provider: heroku
  api_key:
    secure: hIcTC5wx42SG1gW7i2fBq2ssNWb0F/FCvCa3UbpDucEzwGRuC08XEg9t35NQWArga9m2i4F8nD5YNu+H+pMfa+wrimq3YTdD7tpErQA2kutXYjHLzlZYzceFbnNGyLiHjdS4NyrjOgGKgT4wBJ9l2ma5WZyyx2GxBscqTXuUia8UzNng5j063m30E0I5w2uQkm1SlcAN4GWy/DrfxcaHPGaMULo62AapKPrWPOfoXYUeH74//pCL54h5taVh+fkPVbtkUQHcwIbQUmJA2w8C1oc7GEydGkqU5VHt+iVtlotBWU691cK5hAhdnPzzrid4HhRy5nWgN3qr3HJFLmL87BhyypUgovn3dYKptvSfiNt9twgN74IZVIw3VyaZDhIzMvP7CtX0JiKZ3mthWwTZkSk0PzuLwt28nRbpeQzwBe9h44OIaYojhHvPDWUWRuDMyQvx1vgaBsS+JZG451rsEsLeNDUpt+a2UBxBt3QaoImf0ptvJuXU7HWIwwBef0sWIBh0d5+3Jg/cfssHkcI1EvnFjRXVpfuLj0DcgdELWQl+LWf/Zx0EOK8gRhmV4Fv+ITWXxpYPjibWKdkBP6tgUEVMe3js4QSL2qobQMeFk45fHpL/AHrEK5wdGrm0P3bDXF7avms/ZrX8ikCM+Lyv2O+nsdoLtZlYcH/mX1B8rFs=
  app: Hello-World
  on:
    repo: uiowa-cs-5800-0001-fall-2017/Hello-World
  language: node_js
  node_js: 
    - "node"